# -*- coding: utf-8 -*-
"""Curso relâmpado de Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hCGKvYsrEWH_sXMQyOdvpWawLIFGlMEs

# Curso rápido de Python

Por favor, note que isso não tem a intenção de ser um curso abrangente de Python ou da programação em geral. Se você não possui experiência de programação, sugiro que dê uma olhada em um outro curso de José Portilla: [Complete Python Bootcamp](https://www.udemy.com/Complete-python-bootcamp/?CouponCode=PY20).

** Este notebook é apenas uma referência de código para os vídeos, não há explicações por escrito aqui **

Este notebook vai apenas passar pelos tópicos básicos em ordem:

* Tipos de dados
    * Numbers
    * Strings
    * Printando
    * Listas
    * Dicionários
    * Boleanos
    * Tuplas
    * Sets
* Operadores de comparação
* if,elif, else
* for Loops
* while Loops
* range()
* list comprehension
* funções
* expressões lamda
* map e filter
* métodos
____

## Tipos de dados

### Numéricos
"""

1 + 1

1 * 3

1 / 2

2 ** 4

4 % 2

5 % 2

(2 + 3) * (5 + 5)

"""### Definição de variáveis"""

# Não se pode iniciar uma variável com números ou carateres especais
nome_da_variavel = 2

x = 2
y = 3

z = x + y

z

"""### Strings"""

'Citação simples'

"Citações duplas"

"""### Printando"""

x = 'ola'

x

print(x)

num = 12
nome = 'Sam'

print('Meu número é: {one}, e meu nome é: {two}'.format(one=num,two=nome))

"""### Listas"""

[1,2,3]

['hi',1,[1,2]]

minha_lista = ['a','b','c']

minha_lista.append('d')

minha_lista

minha_lista[0]

minha_lista[1]

minha_lista[1:]

minha_lista[:1]

minha_lista[0] = 'NOVO'

minha_lista

nest = [1,2,3,[4,5,['target']]]

nest[3]

nest[3][2]

nest[3][2][0]

"""### Dicionários"""

d = {'chave1':'item1','chave2':'item2'}

d

d['chave1']

"""### Booleanos"""

True

False

"""### Tuplas"""

t = (1,2,3)

t[0]

t[0] = 'NEW'

"""### Sets"""

{1,2,3}

{1,2,3,1,2,1,2,3,3,3,3,2,2,2,1,1,2}

"""## Operadores de comparação"""

1 > 2

1 < 2

1 >= 1

1 <= 4

1 == 1

'oi' == 'tchau'

"""## Operadores lógicos"""

(1 > 2) and (2 < 3)

(1 > 2) or (2 < 3)

(1 == 2) or (2 == 3) or (4 == 4)

"""## if,elif, else"""

if 1 < 2:
    print('Sim!')

if 1 < 2:
    print('Primeiro')
else:
    print('Último')

if 1 > 2:
    print('Primeiro')
else:
    print('Último')

if 1 == 2:
    print('Primeiro')
elif 3 == 3:
    print('Meio')
else:
    print('Último')

"""## for Loops"""

seq = [1,2,3,4,5]

for item in seq:
    print(item)

for item in seq:
    print('!')

for outra_coisa in seq:
    print(outra_coisa+outra_coisa)

"""## while Loops"""

i = 1
while i < 5:
    print('i is: {}'.format(i))
    i = i+1

"""## range()"""

range(5)

for i in range(5):
    print(i)

list(range(5))

"""## list comprehension"""

x = [1,2,3,4]

out = []
for item in x:
    out.append(item**2)
print(out)

[item**2 for item in x]

"""## Funções"""

def my_func(param1='default'):
    """
    Documentação da função vai aqui.
    """
    print(param1)

my_func

my_func()

my_func('novo parametro')

my_func(param1='novo parametro')

def square(x):
    return x**2

out = square(2)

print(out)

"""## Expressões lamda"""

def vezes2(var):
    return var*2

vezes2(2)

lambda var: var*2

"""## map e filter"""

seq = [1,2,3,4,5]

map(vezes2,seq)

list(map(vezes2,seq))

list(map(lambda var: var*2,seq))

filter(lambda item: item%2 == 0,seq)

list(filter(lambda item: item%2 == 0,seq))

"""## Métodos"""

st = 'Olá, me chamo Sam'

st.lower()

st.upper()

st.split()

tweet = 'Dale Grêmio! #Gremio'

tweet.split('#')

tweet.split('#')[1]

d

d.keys()

d.items()

lst = [1,2,3]

lst.pop()

lst

'x' in [1,2,3]

'x' in ['x','y','z']